### ISSUE TITLE
reprex ORPHANED on CRAN

### ISSUE THREAD

**Issue by barryrowlingson** [tidyverse/reprex#171]
CRAN is giving reprex as ORPHANED:

https://cran.r-project.org/web/packages/reprex/index.html

```
Published: | 2018-01-26
Author: | Jennifer Bryan [aut, cre],   David Robinson [aut]
Maintainer: | ORPHANED
```

**Comment by cderv** [comment]
There seems to be an issue with this CRAN release. The `DESCRIPTION` is not the one present here in github. 
I have noticed it with the version number **1.2** which is not bumped here in GH, nor in the `DESCRIPTION` file nor in  `NEWS.md`, no new tag and no new release in GH. 

Something is off. Instead of opening a new issue for version number, I add this infos in your issue as I think it is related.

**Comment by yutannihilation** [comment]
Something seems wrong with the package (the email address is masked).

```console
$ wget https://cran.rstudio.com/src/contrib/reprex_0.1.2.tar.gz
$ tar xzf reprex_0.1.2.tar.gz reprex/DESCRIPTION
$ tail -3 reprex/DESCRIPTION
X-CRAN-Original-Maintainer: Jennifer Bryan <...@gmail.com>
X-CRAN-Comment: Orphaned on 2018-01-26 for policy violations, and
        offending code disabled.
```

Maybe is "policy violations" related to the errors in the package checks?: https://cran.rstudio.com/web/checks/check_results_reprex.html?

**Comment by jennybc** [comment]
The "update" was not made by me but rather by BDR, commenting out lines of code and orphaning the package. I had nothing to do with that version.

reprex was basically ready for new release in December, when several maintainers whose packages use clipr were notified that CRAN wanted different behaviour around clipboard processes (https://github.com/mdlincoln/clipr/issues/30). So that suggests a few changes to be made on top of the other features and fixes already in the new version, which is fine. But ...

The dev version of reprex depends on the dev version of callr. So callr needs to submit first. But the dev version of callr depends on the dev version of processx. So processx needs to update first. And it has been stuck at CRAN for ?months? and the situation is very ... opaque. I explained this in an email to CRAN on Jan 23, which apparently was not read. I re-explained in another email yesterday, which has now been read and received a response. But now it is difficult to make it as if the orphaning had never happened, which would have been the right outcome.

So now it will take a little while to sort out the situation. I would recommend installing and running the dev version of reprex from GitHub in the meantime.

**Comment by yutannihilation** [comment]
Thanks for the detail. What a pity... 😢 

> And it has been stuck at CRAN for ?months?

IIRC, I saw processx 3.0.0 to 3.0.3 is on the CRAN queue (ftp://cran.r-project.org/incoming/inspect/) during this two months. Maybe the retry rate was so fast that the package got some penalty from CRAN...?

Anyway, hope the situation will get better soon!

**Comment by jennybc** [comment]
> I saw processx 3.0.0 to 3.0.3 were on the CRAN queue during this two months

It's complicated. But there are important Windows bug fixes in there, so yes it would be great to get it unstuck.

**Comment by yutannihilation** [comment]
Ah, I see.

**Comment by MilesMcBain** [comment]
@dpastoor Check HW's comments in https://github.com/mdlincoln/clipr/issues/30.

I applied this reasoning to modifications made to `datapasta` to comply with the policy. So far I haven't had any of my code altered(!) so looking good.

**Comment by jennybc** [comment]
I am about to resubmit again with this argument explicitly in the CRAN comments.

As @MilesMcBain says, the update to datapasta was accepted *after* the change to the policy. The rio package also writes unconditionally to the clipboard and has had no modifications made to its code, nor has it been ORPHANED. I have not yet done an exhaustive search of CRAN, but perhaps there are even more.

In all known cases (datapasta, rio, reprex, usethis), I believe usage of the function and/or package implies that user wants the package read/write the clipboard. That is the primary reason to call these functions.

Through other channels, I have also asked for explicit confirmation that the clipboard policy is to be applied consistently to all CRAN packages and maintainers.
