### ISSUE TITLE
reprex doesn't handle multi-line strings with single quotes

### ISSUE THREAD

**Issue by kevinushey** [tidyverse/reprex#202]
If I attempt to reprex this R script:

```R
code <- "
#' hello, world!
"

writeLines(code)
```

I see the following:

```
code <- "
#> Error: <text>:1:9: unexpected INCOMPLETE_STRING
#> 1: code <- "
#>             ^
hello, world!

"

writeLines(code)
#> Error: <text>:1:1: unexpected INCOMPLETE_STRING
#> 2: 
#> 3: writeLines(code)
#>    ^
Created on 2018-09-07 by the reprex package (v0.2.0.9000).
```

I bumped into this while trying to put together a reprex for the `roxygen2` package.

**Comment by crew102** [comment]
I think this is an issue with `rmarkdown::render()`, which `reprex()` relies on to render the user's reprex.

**Comment by kevinushey** [comment]
You're right! Thanks for taking the time to narrow that down; I'll close this.

**Comment by jennybc** [comment]
Yeah I concur. I looked into this on the plane and it happens even if you try to `render()` that code saved in `.R` script.

**Comment by pgensler** [comment]
Is this fixed? This is still happenning on Windows 10:

**Comment by batpigandme** [comment]
@pgensler, if you're still running into the issue, it's source would still be from `rmarkdown::render()`. It should be fixed (since https://github.com/rstudio/rmarkdown/issues/1444 is closed), but, if not, the source remains upstream. 
It looks like https://github.com/yihui/knitr/issues/1621 might be related, which is still open.
