### ISSUE TITLE
"Run as reprex" button in the RStudio IDE?

### ISSUE THREAD

**Issue by wlandau** [tidyverse/reprex#227]
Can  an add-in accomplish this? I would have posted to the [IDE's tracker](https://github.com/rstudio/rstudio), but it is a lot busier.

![button](https://user-images.githubusercontent.com/1580860/50304337-a77d7f00-045d-11e9-9615-52e477fd5187.png)

**Comment by batpigandme** [comment]
I realize the IDE team's got a lot more going on in their repo, but, since this would have to be implemented from their end, that's really a better place to keep track of this feature request. Unfortunately, I can't transfer issues across GitHub organizations. So, if you wouldn't mind opening this over there, that'd be great.

Thanks

**Comment by wlandau** [comment]
Sure, I would be happy to.

**Comment by batpigandme** [comment]
Thanks, Will!
