### ISSUE TITLE
differences between `reprex_addin()` vs `reprex()` on Wayland

### ISSUE THREAD

**Issue by pat-s** [tidyverse/reprex#266]
Just a quick drop of my usage experience on Wayland (successor of X window manager on Linux) using `wl-clipboard` as the underlying clipboard library.

`reprex_addin()` does not put the results on the clipboard for me. When running it the second time, it states that is was unsuccessful in putting the results to the clipboard.

`reprex::reprex()` works without issues. If the input is on the clipboard, the reprex is returned on the clipboard.

reprex v0.3

**Comment by jennybc** [comment]
I'm afraid I don't have ready access to this environment (Wayland).

I don't have any immediate theories as to why `reprex::reprex()` works fine with the clipboard when run from the console but not via the gadget.

The various moving parts are Shiny, rstudioapi, and clipr.

I'm going to close for now since I don't have plans to stand up the environment necessary to reproduce, but if someone provided more info or fixed it, I'd be happy to hear about it.
