### ISSUE TITLE
Add Slack as a target venue

### ISSUE THREAD

**Issue by ColinFay** [tidyverse/reprex#272]
It would be nice if we could have a "Slack" as a Target venue: I find myself sharing a lot of code to Slack, but using reprex I have to remove the `r` from the first backticks and change the reprex summary in the end. 

Expected output: 

<img width="617" alt="Screenshot 2019-07-16 at 11 06 35" src="https://user-images.githubusercontent.com/17936236/61281377-d40e3500-a7b9-11e9-96ff-c8135c2fa98f.png">

**Comment by jennybc** [comment]
Use the existing `venue = "R"` for Slack.

I suppose we could create an alias "slack" for "r", the same way that Discourse (`"ds"`) is just an alias for the default `"gh"`.

**Comment by scottcame** [comment]
@jennybc solution avoids removal of the `r` after the opening backticks and the extraneous stuff at the end.  But requires manually adding the opening and closing three-backtick sequence.

The ubiquity of Slack, and in particular the use of Slack for one of the more popular R learning platforms (R4DS), suggests that having reprex output that is ready-to-go for Slack, without any editing, would be super beneficial.

@jennybc would you welcome a PR for this?

**Comment by jennybc** [comment]
It's a tough call. I usually post these as Slack **snippets**, because then they get syntax highlighting, are collapsible, etc. And in that case you don't want the backticks.

**Comment by ColinFay** [comment]
Maybe we can have both?

**Comment by scottcame** [comment]
In private (company/client) Slacks as well as R4DS, what I tend to see is smaller code samples being pasted directly inline (enclosed in backticks) with larger ones posted as snippets. Both approaches have their place IMO.

I like the idea of enabling both. As you suggest, the snippet approach is already supported with `venue='r'`.

**Comment by scottcame** [comment]
I dug into this issue a bit more. It turns out that what's most needed here is the ability to suppress the `r` syntax highlight directive on the opening line of a fenced code block. It's already possible to suppress the advertising footer with `advertise=FALSE`.

I added a `plain-md` venue that suppresses the syntax highlight indicator (which is unfortunately hardcoded in the output of `rmarkdown::render`) and suppresses the ad by default.

https://github.com/tidyverse/reprex/pull/283
