### ISSUE TITLE
reprex is not capturing output from REprintf

### ISSUE THREAD

**Issue by mattfidler** [tidyverse/reprex#278]
Reprex doesn't capture `stderr` from `REprintf` so error from this source are not shown;  An example of this is:

https://github.com/nlmixrdevelopment/nlmixr/issues/204#issuecomment-515520699

``` r
Rcpp::cppFunction("RObject testMsg(){\n REprintf(\"Capture REprintf\\n\");\nreturn R_NilValue;\n}")
testMsg()
#> NULL

Rcpp::cppFunction("RObject testMsg2(){\n Rprintf(\"Capture Rprintf\\n\");\nreturn R_NilValue;\n}")
testMsg2()
#> Capture Rprintf
#> NULL

message("capture message\n")
#> capture message
cat("capture cat\n")
#> capture cat
```

<sup>Created on 2019-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Here is the output on the interactive console:

```r
> testMsg()
Capture REprintf
NULL
> 
> Rcpp::cppFunction("RObject testMsg2(){\n Rprintf(\"Capture Rprintf\\n\");\nreturn R_NilValue;\n}")
> testMsg2()
Capture Rprintf
NULL
> 
> 
> 
> message("capture message\n")
capture message

> cat("capture cat\n")
capture cat
> 
```

Unfortunately, `REprintf` is required for printout when the low level when `OpenMP` is used, or the R stack can get corrupted.

**Comment by jennybc** [comment]
reprex just inherits the behaviour of rmarkdown/knitr, so that's where you'd really need to take this up.

However, note that `reprex()` will capture standard output and error, albeit not nice interleaved like "normal" output.

When I reprex your code with `reprex(std_out_err = TRUE)`, I can get the output from `REprintf()`, but in separate section. That helps a little.

``` r
Rcpp::cppFunction("RObject testMsg(){\n REprintf(\"Capture REprintf\\n\");\nreturn R_NilValue;\n}")
testMsg()
#> NULL

Rcpp::cppFunction("RObject testMsg2(){\n Rprintf(\"Capture Rprintf\\n\");\nreturn R_NilValue;\n}")
testMsg2()
#> Capture Rprintf
#> NULL

message("capture message\n")
#> capture message
cat("capture cat\n")
#> capture cat
```

standard output and standard error
``` sh
Capture REprintf
```
<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by jennybc** [comment]
And here's a rich stackoverflow thread on why this hasn't already been "fixed" in knitr. It's just not very simple.

https://stackoverflow.com/questions/36928322/how-to-capture-the-output-of-system

**Comment by mattfidler** [comment]
Hi @jennybc 

Thank you for your response.

I agree it isn't simple;  I have tried to capture it myself for other packages.  

It also makes me wonder about when things are going to `stderr` but will not show up in R.  I currently am not aware of anything.

Thanks for work-around.

**Comment by mattfidler** [comment]
A possible request would be to change `std_out_err = TRUE` to `std_out_err = NULL` to be the default behavior and change the output from:

``` r
Rcpp::cppFunction("RObject testMsg2(){\n Rprintf(\"Capture Rprintf\\n\");\nreturn R_NilValue;\n}")
testMsg2()
#> Capture Rprintf
#> NULL

message("capture message\n")
#> capture message
cat("capture cat\n")
#> capture cat
```

standard output and standard error
``` sh
-- nothing to show --
```
<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To 

``` r
Rcpp::cppFunction("RObject testMsg2(){\n Rprintf(\"Capture Rprintf\\n\");\nreturn R_NilValue;\n}")
testMsg2()
#> Capture Rprintf
#> NULL

message("capture message\n")
#> capture message
cat("capture cat\n")
#> capture cat
```
<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

When there is nothing to show.

I could even add the feature if you wish.

**Comment by mattfidler** [comment]
And when there *is* something to show, the `reprex` actually shows something is happening, as in your example.

**Comment by jennybc** [comment]
Feel free to open a new issue about whether to change the default for `std_out_err` and/or to put it under the control of an option. I'm hesitant to turn it on by default, because now we're vulnerable to any glitches in how that works in callr. So I lean towards: keep the default as `FALSE` but make it possible for people who frequently reprex with packages where they need `std_out_err` to set a personal default of `TRUE`.

**Comment by mattfidler** [comment]
Ok.  I opened an issue.  

Unfortunately people submitting issues may not know if they need to capture `std_out_err` but are trying to submit an issue to maintainers.  But the glitches in callr may be problematic.
