### ISSUE TITLE
Workaround needed to render bash shell code when reporting R issue

### ISSUE THREAD

**Issue by jooyoungseo** [tidyverse/reprex#282]
Sometimes, I need to create a reproducible R code from bash shell when reporting issues.
I was wondering if there would be any way to render `bash` scripts in `reprex::reprex()`. I was attempting to render the following code using `rmarkdown::github_document` alternatively; however, it fails when error occurs while rendering bash scripts.
In sum, I think we need a way to make a reproducible bash code including its error messages for reporting issue.
Below is an example bash code I was attempting to report to `xaringan` package including its error message; however, I could not find any way to do. Thus, I just had to report its input code without any output message.

```{bash}
# Creating a sample template Rmd file:
Rscript --vanilla -e "rmarkdown::draft('resume.Rmd', 'html-resume', 'pagedown', create_dir = FALSE, edit = FALSE)"

# Render the sample Rmd file using shell:
Rscript --vanilla -e "xaringan::infinite_moon_reader('resume.Rmd')"
```

**Comment by jennybc** [comment]
> I was wondering if there would be any way to render bash scripts in `reprex::reprex()`

At its heart, reprex "just" writes code to an R script, then calls `rmarkdown::render()`.

So ... what you want would really require that we write code to chunks inside an `.Rmd`, which has a mechanism for non-R chunks.

I have long contemplated this and have wondered why I chose `.R` instead of `.Rmd`. But yet here we are.

I don't think there is any way for you to reprex little bits of bash with `reprex::reprex()` right now.

**Comment by jennybc** [comment]
I've opened #287 about the `.Rmd` workflow, which is what it would take to solve this. Closing this, since they are now linked.
