### ISSUE TITLE
reprex(libpath = )

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/reprex#316]
I'm looking for a way to run a reprex with an alternative library path, i.e. 

```r
reprex::reprex(libpath = "../bench-libs/0.8.3")
```

As I develop a 📦 I sometimes keep a library with the released version available nearby, with `callr::r()` I can then run code "inside" that library. Would be nice to be able to also do it in a reprex. 

Although, writing this issue, I realize that I can do: 

```r
withr::with_libpaths("../bench-libs/0.8.3/", reprex())
```

**Comment by jennybc** [comment]
I think I'm going to leave this alone for now, since you have a decent workaround.

The right way to do this would be to gain an argument and wire that up to the [`libpath` argument of `callr::r()`](https://callr.r-lib.org/reference/r.html#arguments). I think this scopes the altered library path more precisely than the `withr::with_libpaths()` approach. But I'd rather wait and see if this comes up again and if someone really needs the "right" implementation instead of the workaround.
