### ISSUE TITLE
Reprex not reproducing the actual error shown the console

### ISSUE THREAD

**Issue by PublicHealthDataGeek** [tidyverse/reprex#325]
Hello

I am using Ubuntu 20.04 and R4.  I have been having an issue with another package that I wanted to reprex.  

When I copy the code and then reprex I get the below output.  However this does not match the error I see in the console (see further down).    I would be grateful for any thoughts...  

Best wishes
Caroline

```r
# Reprex output
``` r
trails %>%
  st_transform(st_crs(franconia)) %>%
  st_intersection(franconia[franconia$district == "Oberfranken", ]) %>%
  st_collection_extract("LINE") %>%
  mapview(color = "red", lwd = 3, layer.name = "trails") +
  mapview(franconia, zcol = "district", burst = TRUE) +
  breweries
#> Error in trails %>% st_transform(st_crs(franconia)) %>% st_intersection(franconia[franconia$district == : could not find function "%>%"
```

<sup>Created on 2020-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```

Actual console output is: 
`trails` %>%'
'   st_transform(st_crs(franconia))` %>%'
'   st_intersection(franconia[franconia$district == "Oberfranken", ]) %>%'
'   st_collection_extract("LINE") %>%' 
'   mapview(color = "red", lwd = 3, layer.name = "trails") + mapview(franconia, zcol = "district", burst = TRUE) + breweries'
although coordinates are longitude/latitude, st_intersection assumes that they are planar
Error in .subset(x, j) : invalid subscript type 'list'
In addition: Warning message:
attribute variables are assumed to be spatially constant throughout all geometries

**Comment by PublicHealthDataGeek** [comment]
sorry, I shoudl have said that the packages installed are mapview, tidyverse and sf.

**Comment by jennybc** [comment]
If I follow, your first code snippet is _not_ self-contained.

`%>%` is not present in base R. So that's the first (and only) error reported by reprex, which takes your exact code over into a fresh R session for execution.

The error you report seeing in the Console is affected by code you've already run there (and that you didn't include in your reprex or in this thread). You are missing several `library()` calls. So you've sort of answered your own question with this:

> sorry, I shoudl have said that the packages installed are mapview, tidyverse and sf.

Tthe code snippet you provide to `reprex()` should look more like this:

``` r
library(mapview)
library(tidyverse)
library(sf)

trails %>%
  st_transform(st_crs(franconia)) %>%
  st_intersection(franconia[franconia$district == "Oberfranken", ]) %>%
  st_collection_extract("LINE") %>%
  mapview(color = "red", lwd = 3, layer.name = "trails") +
  mapview(franconia, zcol = "district", burst = TRUE) +
  breweries
```

But you're also going to struggle until the snippet defines the `franconia` object (unless that's exported by one of the packages).

**Comment by PublicHealthDataGeek** [comment]
Thank you very much for getting back to me, Jenny.  Bit of a newbie I am afraid so thanks for being gentle.  

I didnt realise that you needed to include the library calls in the code that you copy!  The example I looked at 'how to generate a reprex' just had code (as it wasnt using any packages).  

Many thanks
