### ISSUE TITLE
Backticks/code fence is missing from default output

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/reprex#338]
In the current development version of reprex, if I run a reprex through the addin, or using `reprex::reprex()` the markdown output is missing fencing, but is indented (see below). This works on GitHub, but backticks need to be added for community/Discourse. Looking at the CommonMark issue linked in NEWS, it sounds like it supports both [fenced](https://spec.commonmark.org/0.28/#fenced-code-blocks) and un-fenced versions, so I'm wondering if the fencing might be a better default.

````
    dchisq(1, df = 1:3)
    #> [1] 0.2419707 0.3032653 0.2419707

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
````
With reprex 0.3.0 I get:
````
``` r
dchisq(1, df = 1:3)
#> [1] 0.2419707 0.3032653 0.2419707
```

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
````

**Comment by cderv** [comment]
Hi ! 

Just shiming in because we already encountered this in https://github.com/tidyverse/reprex/issues/330 and it was due to an issue in Pandoc 2.10. It has been fixed in new release of pandoc.

With last pandoc 2.11.0.2 (included in last daily I think) I got this 

````
``` r
dchisq(1, df = 1:3)
#> [1] 0.2419707 0.3032653 0.2419707
```

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
````

Can you check your pandoc version ? 

Faulty Pandoc 2.10 was included in one of the RStudio dailies at some point. 

Hope it helps.

**Comment by batpigandme** [comment]
Thanks, @cderv. You were right!
Daily I was running:
```r
rmarkdown::pandoc_version()
#> [1] ‘2.10.1’
```
Today's daily:
```r
rmarkdown::pandoc_version()
#> [1] ‘2.11.0.2’
```

🎉 
````
``` r
dchisq(1, df = 1:3)
#> [1] 0.2419707 0.3032653 0.2419707
```

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
````
