### ISSUE TITLE
Missing warning in reprex when expecting warning with a specific class

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/reprex#397]
This is a very rare and minor bug.

When testing warnings using `testthat`, some reprexes are missing the warning if the test was on the class of the warning:

``` r
f = function(){
    rlang::warn("foo", class="bar")
}
f() #warning
#> Warning: foo
testthat::expect_warning(f(), class="bar") #no warning
testthat::expect_warning(1) #warning
#> Error: 1 did not produce any warnings.
testthat::expect_warning(f(), class="barrrrrrr") #missing warning
```
<sup>Created on 2021-10-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If you try this in the console, the last line indeed outputs a warning.

**Comment by jennybc** [comment]
Yes, I can reproduce this.

However I don't see how this could be due to anything done here in reprex itself. It's either to do with testthat or rlang. To the extent that reprex can/will worry about this, I think it's covered by #230, which is about how reprex should interact with rlang's controls re: conditions.
