### ISSUE TITLE
Suppress package startup messages automatically

### ISSUE THREAD

**Issue by olivroy** [tidyverse/reprex#420]
I wonder if there was an option to suppress these types of messages automatically, either via an option  that can be put in .Rprofile. 
maybe :
```r
options(reprex.startup = FALSE) 
```
or  `reprex::reprex(startup = FALSE)`
I agree other warnings are useful, but these are really useless. It is also annoying and ugly to put `suppressPackageStartupMessages()` all the time.
``` r
library(tidyverse)
#> Warning: le package 'tidyverse' a été compilé avec la version R 4.1.1
#> Warning: le package 'ggplot2' a été compilé avec la version R 4.1.3
#> Warning: le package 'tibble' a été compilé avec la version R 4.1.3
#> Warning: le package 'tidyr' a été compilé avec la version R 4.1.2
#> Warning: le package 'readr' a été compilé avec la version R 4.1.2
#> Warning: le package 'purrr' a été compilé avec la version R 4.1.1
#> Warning: le package 'stringr' a été compilé avec la version R 4.1.1
library(sf)
#> Warning: le package 'sf' a été compilé avec la version R 4.1.2
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
```

<sup>Created on 2022-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jennybc** [comment]
By default, reprex **does** suppress the start messages for tidyverse packages:

``` r
library(tidyverse)
```

<sup>Created on 2022-06-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

So it you get different behaviour, something in your setup, e.g. in `.Rprofile`, must be interfering with that.

You can read more about the `reprex.tidyverse_quiet` option in the docs:

https://reprex.tidyverse.org/reference/reprex_options.html

I can't suppress startup messages in general because they aren't generally thrown with a class that allows selective suppression. I can do it for the tidyverse (and tidymodels) because tidyverse and tidymodels make this configurable.
