### ISSUE TITLE
Trailing text (prose) not rendered for expression input

### ISSUE THREAD

**Issue by Henrik-P** [tidyverse/reprex#89]
If a `reprex` ends with text, the text following the code is not rendered. I.e. this `reprex` code:

    reprex({
    #' If a `reprex` ends with text, the text following the code is not rendered
    x <- 1:2 
    #' Trailing text
    })

...generates this:

If a `reprex` ends with text, the text following the code is not rendered

``` r
x <- 1:2
```
-------

    reprex({
      #' Add some code after the trailing text to render it
      x <- 1:2
      #' Non-trailing text is rendered
      x
      })
Add some code after the trailing text to render it

``` r
x <- 1:2
```

Non-trailing text is rendered

``` r
x
#> [1] 1 2
```

**Comment by krlmlr** [comment]
This looks like an issue with `knitr::spin()`, can you please double-check?

**Comment by jennybc** [comment]
AFAICT this problem is specific to expression input and is because R's source references do not contain the trailing comment. As long reprex uses the "srcref" attribute, this is going to be a problem. The examples show this and that I could append `#+ echo = FALSE; invisible()` to the source when it derives from an expression to prevent this. Still deciding if it is worth it.

---
Non-expression input:

```r
reprex(input = c("1:2", "#' Trailing text"))
```

Result:

``` r
1:2
#> [1] 1 2
```

Trailing text

---
Expression input:

```r
reprex(input = c("1:2", "#' Trailing text"))
```

Result:

``` r
1:2
#> [1] 1 2
```
---
Expression input with a protective end-cap:

```r
reprex({
  1:2 
  #' Trailing text
  #+ echo = FALSE
  invisible()
})
```

Result:
``` r
1:2
#> [1] 1 2
```

Trailing text

**Comment by jennybc** [comment]
Pretty sure it's not practical to address this. Trailing text is a reason to use the `input` argument or clipboard.

**Comment by jennybc** [comment]
OK I am going to fix this.

**Comment by jennybc** [comment]
After the fix, with this input:

```r
reprex({
#' If a `reprex` ends with text, the text following the code is NOW rendered
x <- 1:2 
#' Trailing text woot!
})
```

Output:

If a `reprex` ends with text, the text following the code is NOW rendered

``` r
x <- 1:2
```

Trailing text woot!
